src/Entity/Property.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;

/**
 * @Vich\Uploadable()
 */
class Property
{
    const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz',
    ];
    /**
     * @var int
     */
    private $id;
    /**
     * @var string | null
     */
    private $filename;
    /**
     * @var File | null
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="filename")
     */
    private $imageFile;
    /**
     * @var string
     */
    private $title;
    /**
     * @var string
     */
    private $description;
    /**
     * @var int
     */
    private $surface;
    /**
     * @var int
     */
    private $rooms;
    /**
     * @var int
     */
    private $bedrooms;
    /**
     * @var int
     */
    private $floor;
    /**
     * @var int
     */
    private $price;
    /**
     * @var int
     */
    private $heat;
    /**
     * @var string
     */
    private $city;
    /**
     * @var string
     */
    private $adress;
    /**
     * @var int
     */
    private $postal_code;
    /**
     * @var bool
     */
    private $sold = false;
    /**
     * @var \DateTime
     */
    private $created_at;
    /**
     * @var array
     */
    private $options;
    /**
     * @var \DateTime
     */
    private $updated_at;

    public function __construct(
        string $title,
        string $description,
        int $surface,
        int $rooms,
        int $bedrooms,
        int $floor,
        int $price,
        int $heat,
        string $city,
        string $adress,
        int $postal_code,
        bool $sold,
        array $options = [],
        File  $imageFile = null,
        string $filename = null
    )
    {
        $this->title = $title;
        $this->description = $description;
        $this->surface = $surface;
        $this->rooms = $rooms;
        $this->bedrooms = $bedrooms;
        $this->floor = $floor;
        $this->price = $price;
        $this->heat = $heat;
        $this->city = $city;
        $this->adress = $adress;
        $this->postal_code = $postal_code;
        $this->sold = $sold;
        $this->created_at = new \DateTime();
        $this->imageFile = $imageFile;
        $this->filename = $filename;
        $this->updated_at = new \DateTime();
        $this->options = new ArrayCollection();
        foreach ($options as $option) {
            $this->options->add($option);
        }
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt(): \DateTime
    {
        return $this->updated_at;
    }

    /**
     * @param \DateTime $updated_at
     * @return Property
     */
    public function setUpdatedAt(\DateTime $updated_at): Property
    {
        $this->updated_at = $updated_at;
        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;
        return $this;
    }
    public function getSlug(): string
    {
        $slugify = new Slugify();
        return $slugify->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;
        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;
        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;
        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;
        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;
        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;
        return $this;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;
        return $this;
    }

    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;
        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;
        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;
        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;
        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): self
    {
        $this->created_at = $created_at;
        return $this;
    }

    /**
     * @return array|Option[]
     */
    public function getOptions()
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }
        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->removeElement($option)) {
            $option->removeProperty($this);
        }
        return $this;
    }

    public function setOptions(array $options)
    {
        $this->options = new ArrayCollection();
        foreach ($options as $option) {
            $this->options->add($option);
        }

        return $this;
    }

    /**
     * @return string|null
     */
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param string|null $filename
     * @return Property
     */
    public function setFilename(?string $filename): Property
    {
        $this->filename = $filename;
        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File | null $imageFile
     * @return Property
     */
    public function setImageFile(?File $imageFile): Property
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }



}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoices()
            ])
            ->add('options', EntityType::class, [
                'class' => Option::class,
                'choice_label' => 'name',
                'multiple' => true
            ])
            ->add('city')
            ->add('adress')
            ->add('postal_code')
            ->add('sold')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    private function getChoices()
    {
        $choices = Property::HEAT;
        $output = [];
        foreach($choices as $key =>$value){
            $output[$value] = $key;
        }
        return $output;

    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;



use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use App\Repository\PropertyRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ObjectManager;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class PropertyController extends AbstractController
{
    public function __construct(PropertyRepository $repository, EntityManagerInterface $em)
    {
        $this->repository = $repository;
        $this->em = $em;

    }

    /**
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request) : Response
    {
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);

        $properties = $paginator->paginate(
            $this->repository->findAllVisibleQuery($search),
            $request->query->getInt('page',1),
            12
        );

        return $this->render('property/index.html.twig', [
            'properties' => $properties,
            'form' => $form->createView()
        ]);
    }

    /**
     * @return Response
     */
    public function show(Property $property, string $slug): Response
    {
        if ($property->getSlug() !== $slug)
        {
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ], 301);
        }
        return $this->render('property/show.html.twig', [
            'property' => $property,
            'current_menu' => 'properties'
        ]);
    }
}

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Tous nos biens' %}

{% block body %}
    <div class="bg-light">
        <div class="container">
            {{ form_start(form) }}

            <div class="row mt-5">
                <div class="col">
                    {{ form_row(form.minSurface) }}
                </div>
                <div class="col">
                    {{ form_row(form.maxPrice) }}
                </div>
                <div class="col">
                    {{ form_row(form.options) }}
                </div>
                <div class="col">
                    <div class="form-group">
                        <button class="btn btn-primary">Rechercher</button>
                    </div>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>

    <div class="container mt-4">
        <h1>Voir tous nos biens</h1>
            <div class="row">
                {% for property in properties %}
                <div class="col-md-4">
                    {% include('property/property.html.twig') %}
                </div>
                {% endfor %}
            </div>
        <div class="pagination">
            {{ knp_pagination_render(properties) }}
        </div>
    </div>

{% endblock %}

templates/property/property.html.twig
<div class="card mb-4">
    {% if property.filename %}
        <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('thumb') }}" alt="Image" style="width: 100%; height: auto">
        {% else %}
            <img src="{{ 'images/default/empty.jpeg' | imagine_filter('thumb') }}" alt="Image par défault" style="width: 100%; height: auto">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">
            <a href="{{ path('property.show', {slug: property.slug, id: property.id}) }}">{{ property.title }}</a>

        </h5>
        <p class="card-text">{{ property.description | nl2br }}</p>
        <p class="card-text">{{ property.surface }} m2 - {{ property.city }} ({{ property.postalCode }})</p>
        <div class="text-primary" style="font-size: 2rem; font-weight: bold">
            {{ property.formattedPrice }} €
        </div>
    </div>
</div>

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title property.title %}

{% block body %}

    <div class="bg-light">
        <div class="row">
            {% for message in app.flashes('success') %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}

            {% if not form.vars.valid %}
            <div class="alert alert-danger">
                Erreur lors de la saisie des données
            </div>
            {% endif %}
            <div class="col-md-4">

            </div>
            <div class="col-md-4">
                {% if property.filename %}
                    <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('medium') }}" alt="Image"
                         style="width: 100%; height: auto">
                {% else %}
                    <img src="{{ 'images/default/empty.jpeg' | imagine_filter('medium') }}" alt="Image par défault"
                         style="width: 100%; height: auto">
                {% endif %}
            </div>
            <div class="col-md-4">
                <h1>{{ property.title }}</h1>
                <h2>{{ property.rooms }} pièces - {{ property.surface }} m²</h2>
                <div class="text-primary" style="font-size: 4rem; font-weight: bold">{{ property.formattedPrice }}€
                </div>
                <a href="" class="btn btn-primary">Contacter l'agence</a>
                <div id="contactForm" class="mt-4">
                    {{ form_start(form) }}
                    <div class="row">
                        <div class="col">{{ form_row(form.firstname) }}</div>
                        <div class="col">{{ form_row(form.lastname) }}</div>
                    </div>
                    <div class="row">
                        <div class="col">{{ form_row(form.phone) }}</div>
                        <div class="col">{{ form_row(form.email) }}</div>
                    </div>
                    {{ form_rest(form) }}
                    <div class="form-group">
                        <button class="btn btn-primary">Envoyer</button>
                    </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
    </div>

    <div class="container mt-4">

        <nav class="nav nav-tabs" id="tab"></nav>
        <p>{{ property.description | nl2br }}</p>

        <div class="row">
            <div class="col-md-8">
                <h2>Caractéristiques</h2>
                <table class="table table-dark table-striped">
                    <tr>
                        <td>Surface habitable</td>
                        <td>{{ property.surface }} m²</td>
                    </tr>
                    <tr>
                        <td>Nombre de pièces</td>
                        <td>{{ property.rooms }} pièces</td>
                    </tr>
                    <tr>
                        <td>Chambres</td>
                        <td>{{ property.bedrooms }}</td>
                    </tr>
                    <tr>
                        <td>Etages</td>
                        <td>{{ property.floor }}</td>
                    </tr>
                    <tr>
                        <td>Chauffage</td>
                        <td>{{ property.heatType }}</td>
                    </tr>
                </table>
            </div>

            <div class="col-md-4">
                <h2>Spécificités</h2>
                <ul class="list-group">
                    {% for option in property.options %}
                        <li class="list-group-item">{{ option.name }}</li>
                    {% endfor %}
                </ul>

            </div>
        </div>

    </div>
{% endblock %}